apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpc-helloworld
  name: grpc-helloworld
spec:
  selector:
    matchLabels:
      app: grpc-helloworld
  template:
    metadata:
      labels:
        app: grpc-helloworld
    spec:
      containers:
      - name: grpc-helloworld
        image: quay.io/redhatintegration/grpc-helloworld:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-helloworld
spec:
  selector:
    app: grpc-helloworld
  ports:
  - port: 9000
    targetPort: 9000
